version: "3.8"

networks:
  application:
    driver: bridge

services:

  react-app:
    image: tnfus916/whereqr-front:latest
    ports:
      - 3000:80
    networks:
      - application

  app:
    container_name: backend
    image: baeksujin/whereqr-backend:v2.2
    user: root
    ports:
      - 8080:8080
    restart: always
    networks:
      - application