version: "3.8"

networks:
  application:
    driver: bridge

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: run/secrets/db_password
      MYSQL_DATABASE: where_qr
    networks:
      - application
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    secrets:
      - db_password

#  react-app:
#    image: baeksujin/frontend:v1
#    ports:
#      - 3000:80
#    networks:
#      - application

  app:
    container_name: backend
    image: baeksujin/whereqr:v2
    user: root
    ports:
      - 8080:8080
    restart: always
    networks:
      - application
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-data:

secrets:
  db_password:
    file: db_password.txt